# Generated by Django 3.2 on 2021-05-01 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('Uploadedtime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
